name: bd2dst3pi_env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.2.4=py_0
  - uncertainties=3.1.4=py_0
  - matplotlib=3.3.3=py37h89c1867_0
  - root_pandas=0.7.0=py_0
  - pip:
    - zfit==0.5.5
    - xgboost==1.2.1
    - uproot4==0.1.2
    - awkward1==0.4.3
    - hepstats==0.3.1
    - numpy==1.16.0
    - pandas==1.1.4
    - scipy==1.5.4
    - sklearn==0.0
    - sphinx==3.4.3
    - sphinx-rtd-theme==0.5.1
    - sphinxcontrib-napoleon==0.7